#1 - annotate our genomes + publicly available genomes with no available annotation on NCBI using Helixer web server (https://www.plabipd.de/helixer_main.html)

#2 - convert Helixer .gff files to protein sequence (.faa)
gffread -g {genome}.fasta -y {genome}.faa {GFF}.gff

#3 - run OrthoFinder MSA mode
orthofinder -f ./faa -t 256 -M msa

#4 - run IQ-TREE on SpeciesTreeAlignment.fa file generated by OrthoFinder
iqtree2 -s SpeciesTreeAlignment.fa -B 1000
